:toc: macro
:toclevels: 5
:figure-caption!:

:docker_link: link:https://www.docker.com[Docker]
:trmnl_link: link:https://usetrmnl.com[TRMNL]

= TRMNL BYOS (Ruby/Sinatra)

This project allows you to point a {trmnl_link} device to your own server which can be running on your local network or in the cloud.

toc::[]

== Features

* Allows you to run your own server.
* Includes link:https://puma.io[Puma].
* Includes link:https://www.sqlite.org[SQLite].

== Screencasts

video::3xehPW-PCOM[youtube,role=video]

== Requirements

. link:https://www.ruby-lang.org[Ruby].
. {docker_link} (optional).
. A TRMNL device.

== Setup

To set up project, run:

[source,bash]
----
git clone https://github.com/usetrmnl/byos_sinatra
cd byos_sinatra
bin/setup
----

== Usage

To launch the server, run:

[source,bash]
----
bundle exec puma --config ./config/puma.rb
----

💡 Install link:https://github.com/DarthSim/overmind[Overmind] and run `overmind start` to run with full access to all processes (including remote debugging).

To use the app, open `http://localhost:4567` in your browser to view the app and manage your device(s).

== Development

To contribute, run:

[source,bash]
----
git clone https://github.com/usetrmnl/byos_sinatra
cd byos_sinatra
bin/setup
----

You can also use the IRB console for direct access to all objects:

[source,bash]
----
bin/console
----

Once in the console, you can then do the following:

[source,ruby]
----
# View all devices.
Device.all

# Fetch upcoming render, sorts in descending order by created timestamp.
Images::Fetcher.new.call

# To generate default image.
Images::Creator.new.call "<p>Test.</p>"
#<Pathname:byos_sinatra/public/images/generated/81673687-28b0-4a0c-8efc-ebb344b63cf9.bmp>

# To generate image with custom path.
Images::Creator.new.call "<p>Test.</p>", Pathname.pwd.join("test.bmp")
#<Pathname:byos_sinatra/test.bmp>

# To generate image with custom path and dynamic name.
Images::Creator.new.call "<p>Test.</p>", Pathname.pwd.join("%<name>s.bmp")
#<Pathname:byos_sinatra/c8e41972-c7bb-47d8-b927-ddcf50d20367.bmp>
----

When creating images, you might find this HTML template valuable as a starting point as this let's you use the full capabilities of HTML to create new images for your device.

.HTML Template
[%collapsible]
====
[source,html]
----
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">

    <title>Demo</title>

    <meta charset="utf-8">

    <style type="text/css">
      * {
        margin: 0;
      }
    </style>

    <script type="text/javascript">
    </script>
  </head>

  <body>
    <img src="uri/to/image" alt="Image"/>
  </body>
</html>
----
====

Use of `margin` zero is important to prevent default browser styles from creating borders around your image which will show up when rendered on your device. Otherwise, you have full capabilities to render any kind of page you want using whatever HTML you like. Anything is possible because `Images::Creator` is designed to screenshot your rendered HTML as a 800x480 image to render on your device. If you put all this together, that means you can do this in the console:

.Console Image Generation
[%collapsible]
====
[source,ruby]
----
creator = Images::Creator.new

creator.call(<<~CONTENT, Pathname("public/images/generated/"%<name>s.bmp""))
  <!DOCTYPE html>

  <html lang="en">
    <head>
      <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">

      <title>Demo</title>

      <meta charset="utf-8">

      <style type="text/css">
        * {
          margin: 0;
        }
      </style>

      <script type="text/javascript">
      </script>
    </head>

    <body>
      <h1>Hello, World!</h1>
    </body>
  </html>
CONTENT
----
====

The above will create a new image in the `public/images/generated` folder of this application which will eventually render on your device. 🎉

To build a {docker_link} image, run:

[source,bash]
----
bin/docker/build
----

To work witin your {docker_link} image, run:

[source,bash]
----
bin/docker/console
----

== Tests

To test, run:

[source,bash]
----
bin/rake
----

== Deployment

*Local*

. Configure `APP_URL` within `.env` to where your app is hosted (i.e. `http://192.168.x.x:4567`). 💡 Lack of trailing slash is important.
. Prefix `RACK_ENV=production` before launching the server to run in production mode.
. Retrieve your machine's local IP, ex 192.168.x.x (Mac: `ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}'`)
. Confirm the application works by visiting `http://192.168.x.x:4567/devices` from any device also on the network.
. Point your [forked firmware](https://github.com/usetrmnl/firmware) `API_BASE_URL` ([source](https://github.com/usetrmnl/firmware/blob/2ee0723c66a3468b969c83d7663ffb3f8322ad99/include/config.h#L56)) to same value as `APP_URL`.

*Hosted*

More details to be provided soon.

== Credits

* Built with link:https://alchemists.io/projects/rubysmith[Rubysmith].
* Engineered by {trmnl_link}.
