:toc: macro
:toclevels: 5
:figure-caption!:

:docker_link: link:https://www.docker.com[Docker]
:trmnl_link: link:https://usetrmnl.com[TRMNL]

= TRMNL BYOS (Ruby/Sinatra)

This project allows you to point a {trmnl_link} device to your own server which can be running on your local network or in the cloud.

toc::[]

== Features

* Allows you to run your own server.
* Includes link:https://puma.io[Puma].
* Includes link:https://www.sqlite.org[SQLite].

== Screencasts

video::3xehPW-PCOM[youtube,role=video]

== Requirements

. link:https://www.ruby-lang.org[Ruby].
. {docker_link} (optional).
. A TRMNL device.

== Setup

To set up project, run:

[source,bash]
----
git clone https://github.com/usetrmnl/byos_sinatra
cd byos_sinatra
bin/setup
----

== Usage

[source,bash]
----
bundle exec puma --config ./config/puma.rb
----

💡 Install link:https://github.com/DarthSim/overmind[Overmind] and run `overmind start` to run with full access to all processes (including remote debugging).

== Development

To contribute, run:

[source,bash]
----
git clone https://github.com/usetrmnl/byos_sinatra
cd byos_sinatra
bin/setup
----

You can also use the IRB console for direct access to all objects:

[source,bash]
----
bin/console
----

Once in the console, you can then do the following:

[source,ruby]
----
# View all devices.
Device.all

# Fetch upcoming render, sorts in descending order by created timestamp.
Images::Fetcher.new.call

# To generate default image.
Images::Creator.new.call "<p>Test.</p>"
#<Pathname:byos_sinatra/public/images/generated/81673687-28b0-4a0c-8efc-ebb344b63cf9.bmp>

# To generate image with custom path.
Images::Creator.new.call "<p>Test.</p>", Pathname.pwd.join("test.bmp")
#<Pathname:byos_sinatra/test.bmp>

# To generate image with custom path and dynamic name.
Images::Creator.new.call "<p>Test.</p>", Pathname.pwd.join("%<name>s.bmp")
#<Pathname:byos_sinatra/c8e41972-c7bb-47d8-b927-ddcf50d20367.bmp>
----

To build a {docker_link} image, run:

[source,bash]
----
bin/docker/build
----

To work witin your {docker_link} image, run:

[source,bash]
----
bin/docker/console
----

== Tests

To test, run:

[source,bash]
----
bin/rake
----

== Deployement

*Local*

. Configure `APP_URL` within `.env` to where your app is hosted (i.e. `http://192.168.x.x:4567`). 💡 Lack of trailing slash is important.
. Prefix `RACK_ENV=production` before launching the server to run in production mode.
. Retrieve your machine's local IP, ex 192.168.x.x (Mac: `ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}'`)
. Confirm the application works by visiting `http://192.168.x.x:4567/devices` from any device also on the network.
. Point your [forked firmware](https://github.com/usetrmnl/firmware) `API_BASE_URL` ([source](https://github.com/usetrmnl/firmware/blob/2ee0723c66a3468b969c83d7663ffb3f8322ad99/include/config.h#L56)) to same value as `APP_URL`.

*Hosted*

More details to be provided soon.

== Credits

* Built with link:https://alchemists.io/projects/rubysmith[Rubysmith].
* Engineered by {trmnl_link}.
