name: "byos_sinatra"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - app-db:/workspaces/byos_sinatra/db/sqlite
      - ../..:/workspaces:cached
    environment:
      APP_URL: https://localhost:4443
      DATABASE_URL: sqlite:///workspaces/byos_sinatra/db/sqlite/dev.sqlite
    command: sleep infinity

volumes:
  app-db:
