allowed:
  - SERVER_SOFTWARE
  - SERVER_NAME
  - SERVER_PORT
  - HTTP_BASE64
  - HTTP_FW_VERSION
  - HTTP_ACCESS_TOKEN
  - HTTP_HEIGHT
  - HTTP_HOST
  - HTTP_ID
  - HTTP_REFRESH_RATE
  - HTTP_USER_AGENT
  - HTTP_WIDTH
  - REQUEST_METHOD
  - REQUEST_PATH
  - REQUEST_URI
  - QUERY_STRING
  - PATH_INFO
  - environment
