name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: COMMIT=${{ github.sha }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/byos_sinatra:latest,ghcr.io/${{ github.repository_owner }}/byos_sinatra:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha
