name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      APP_ENV: production
      APP_HOST: 0.0.0.0
      BASE_URL: http://localhost:4567

    steps:
      - name: System Update
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y curl libjemalloc2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build
        run: bundle exec rake

      - name: SimpleCov Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
