name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      APP_HOST: 0.0.0.0
      APP_URL: http://localhost:4567
      RACK_ENV: test

    steps:
      - name: System Update
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y curl libjemalloc2 imagemagick

      - name: Chromium Setup
        uses: nanasess/setup-chromedriver@v2

      - name: Chromium Start
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.head_ref}}

      - name: Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build
        run: bundle exec rake

      - name: SimpleCov Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
